### ISSUE TITLE
[PCB] Replace U3 with a single OR gate

### ISSUE THREAD

**Issue by technobly** [technobly/VEXTREME#15]
## Enhancement

Currently U3 is a quad 74HC32 with only one gate being used.  This was chosen originally to keep the design choices Sprite_tm made for v0.1.  It's a bit cheaper and requires less space to add a single gate version of this.  Keep the package a reasonable size for hand assembly.

https://lcsc.com/product-detail/Gates-and-Inverters_Texas-Instruments_SN74LVC1G32DBVR_Texas-Instruments-Texas-Instruments-SN74LVC1G32DBVR_C10096.html

**Comment by rattboi** [comment]
perhaps we could move the OR logic into the romemu itself? Would require another GPIO though.

**Comment by technobly** [comment]
I ended up adding both options :D
