### ISSUE TITLE
[PCB] Replacement for U4 (SN74LVC8T245DB) which is more generally available (at LCSC)

### ISSUE THREAD

**Issue by technobly** [technobly/VEXTREME#16]
## Enhancement/Bug

- Replacement for U4 (SN74LVC8T245DB) which is more generally available (at LCSC)
- I had tried [this part SN74LVC4245A](https://lcsc.com/product-detail/74-Series_Texas-Instruments-SN74LVC4245APWR_C7859.html) but despite it having the same pinout it doesn't work, the Vectrex ends up not being able to read anything.

**Comment by Alterac** [comment]
Part is already stocking at LCSC, could probably close this
https://lcsc.com/products/74-Series_488.html?q=SN74LVC8T245DB

**Comment by technobly** [comment]
Thanks @Alterac
