### ISSUE TITLE
[feature] Screen saver / mini game

### ISSUE THREAD

**Issue by gtoal** [technobly/VEXTREME#42]
After leaving my vectrex powered up all day it occurred to me that the bright "VEXTREME" at the top of the screen might lead to burn in, in the long term.  Perhaps after a period of inactivity, the default screen could fade out everything except the word VEXTREME, and have it bounce across the screen in a path that eventually covers all positions.  Original screen to be restored on any joystick/button activity.

**Comment by technobly** [comment]
That's a good idea @gtoal !  How about after a timeout, the menu turns into a mini game? It would just be in demo mode until you grabbed the controls, and then, you'd be in!  Button 1 would exit.

**Comment by technobly** [comment]
BTW, I have built Developer Mode #23 from the ground up with screen wear in mind ;-)
