### ISSUE TITLE
menu navigation bug

### ISSUE THREAD

**Issue by gtoal** [technobly/VEXTREME#57]
A the top level, with 3 items showing on the menu, move down so that the second or third item is highlighted.  Then use the joystick to go right, to the last set of items at that level.  If there is only one item on that final page, and you have not moved back up within the page, you can click to start the game thinking that the item is selected, when in fact it is an empty slot that is selected and starting it crashes the vectrex.

**Comment by technobly** [comment]
Thanks for the bug report!  This has been addressed [here in this PR](https://github.com/technobly/VEXTREME/pull/29), but not merged yet because of it being WIP and having some issues still.
