### ISSUE TITLE
Be able to change LED-Brightness

### ISSUE THREAD

**Issue by Badummzi** [technobly/VEXTREME#72]
I'm currently using my Vextreme (btw, extremely happy with it!) without any casing and the only thing, which kind of annoys me, are the really bright leds facing upwards. 

It would be a cool feature, to be able to reduce the led brightness, or turn it off completely!

Alternatively have a DIP switch on the pcb or another firmware, to turn them off?

**Comment by technobly** [comment]
They are pretty bright without a case, and without a label.  If you want to perform a hacky way to dim them, you can open up [LED Test v2 app](https://github.com/technobly/VEXTREME/tree/master/code/led/led-test2) and turn down the brightness, then exit that test app and they should stay set to the same brightness until you power off.  We will be implementing some options that will persist to adjust things in the future.

**Comment by Badummzi** [comment]
Oh, thank you! :D Not an ideal way, but this will work for now! ;)
